# Generated by Django 4.0.5 on 2022-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_cool',
            field=models.BooleanField(default=True),
        ),
    ]
