# Generated by Django 4.0.4 on 2022-05-12 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 8, 57, 13, 902031)),
        ),
    ]
