# Generated by Django 4.0.4 on 2022-05-12 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_snack_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 8, 58, 52, 711526, tzinfo=utc)),
        ),
    ]
